version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/jspc/routes
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go vet -tests github.com/jspc/routes
      - run:
          name: Test
          command: go test -v -race -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload:
          file: coverage.txt
